### ISSUE TITLE
Example use of templatePreviews?

### ISSUE THREAD

**Issue by socialsuiteDan** [forcedotcom/sfdx-analytics#5]
We're having trouble with the preview images in our app template - we follow the syntax from the developer guide but the template-info.json fails to push, would it be possible to add a preview image or two to your example apps so we can see how things work?

**Comment by geoffrothman** [comment]
@reidaelliott fyi ^^

**Comment by geoffrothman** [comment]
@smithgp any ideas here?

**Comment by smithgp** [comment]
Sorry about the delay in responding, it's a big hectic recently :-)
Yes, sorry about the issues in the documentation, I'll send that along to the doc team, and try to get an example staticresource preview image in here shortly.

**Comment by smithgp** [comment]
Hi, @socialsuiteDan, please check out the `staticresources/` in `quick-start/main/default` and the updates to `templatePreviews` in the `Mortgage_Calcuator/template-info.json`.
Also, we're getting the documentation updated.
Thanks for bringing in to our attention!
